apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: openshift-machine-api
  name: cluster-baremetal-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: openshift-machine-api
  name: cluster-baremetal-operator
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - pods
      - secrets
      - services
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
      - replicasets
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - services/finalizers
    resourceNames:
      - cluster-baremetal-operator-metrics
    verbs:
      - update
  - apiGroups:
      - apps
    resources:
      - deployments/finalizers
    resourceNames:
      - cluster-baremetal-operator
    verbs:
      - update
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - servicemonitors
    verbs:
      - get
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-baremetal-operator
rules:
  - apiGroups:
      - config.openshift.io
    resources:
      - clusteroperators
      - clusteroperators/status
    verbs:
      - create
      - get
      - update
  - apiGroups:
      - config.openshift.io
    resources:
      - infrastructures
      - infrastructures/status
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - metal3.io
    resources:
      - provisionings
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: openshift-machine-api
  name: cluster-baremetal-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cluster-baremetal-operator
subjects:
  - kind: ServiceAccount
    namespace: openshift-machine-api
    name: cluster-baremetal-operator
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-baremetal-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-baremetal-operator
subjects:
- kind: ServiceAccount
  namespace: openshift-machine-api
  name: cluster-baremetal-operator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: openshift-machine-api
  name: baremetal-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: openshift-machine-api
  name: baremetal-controller
rules:
  - apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
    verbs:
      - use
    resourceNames:
      - privileged
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - watch
      - list
      - patch
  - apiGroups:
      - metal3.io
    resources:
      - baremetalhosts
    verbs:
      - get
      - list
      - watch
      - update
      - patch
  - apiGroups:
      - metal3.io
    resources:
      - baremetalhosts/status
      - baremetalhosts/finalizers
    verbs:
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: openshift-machine-api
  name: baremetal-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: baremetal-controller
subjects:
  - kind: ServiceAccount
    namespace: openshift-machine-api
    name: baremetal-controller
