apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-baremetal-operator
  namespace: openshift-machine-api
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cluster-baremetal-operator
  template:
    metadata:
      labels:
        name: cluster-baremetal-operator
    spec:
      priorityClassName: system-node-critical
      serviceAccountName: cluster-baremetal-operator
      containers:
        - name: cluster-baremetal-operator
          image: registry.svc.ci.openshift.org/openshift:cluster-baremetal-operator
          command:
          - cluster-baremetal-operator
          resources:
            requests:
              cpu: 10m
              memory: 50Mi
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "cluster-baremetal-operator"
            - name: OPERATOR_VERSION
              value: "0.0.1-snapshot"
            - name: BAREMETAL_IMAGE
              value: "registry.svc.ci.openshift.org/openshift:baremetal-operator"
            - name: IRONIC_IMAGE
              value: "registry.svc.ci.openshift.org/openshift:ironic"
            - name: IRONIC_INSPECTOR_IMAGE
              value: "registry.svc.ci.openshift.org/openshift:ironic-inspector"
            - name: IRONIC_IPA_DOWNLOADER_IMAGE
              value: "registry.svc.ci.openshift.org/openshift:ironic-ipa-downloader"
            - name: IRONIC_MACHINE_OS_DOWNLOADER_IMAGE
              value: "registry.svc.ci.openshift.org/openshift:ironic-machine-os-downloader"
            - name: IRONIC_STATIC_IP_MANAGER_IMAGE
              value: "registry.svc.ci.openshift.org/openshift:ironic-static-ip-manager"
      nodeSelector:
        node-role.kubernetes.io/master: ""
      restartPolicy: Always
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 120
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 120
